global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # NATS Server metrics
  - job_name: 'nats-server'
    static_configs:
      - targets: ['nats-server:8222']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # NATS Exporter metrics
  - job_name: 'nats-exporter'
    static_configs:
      - targets: ['nats-monitor:7777']
    scrape_interval: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Optional: Node exporter for system metrics
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
  #   scrape_interval: 30s
