apiVersion: v1
kind: Secret
metadata:
  name: nats-tls-secret
  namespace: nats-system
type: kubernetes.io/tls
data:
  # Base64 encoded TLS certificates
  # To generate: cat server-cert.pem | base64 -w 0
  # To generate: cat server-key.pem | base64 -w 0
  # To generate: cat ca.pem | base64 -w 0
  tls.crt: ""  # server-cert.pem content
  tls.key: ""  # server-key.pem content
  ca.crt: ""   # ca.pem content
stringData:
  # Alternative way to specify certificates (will be base64 encoded automatically)
  # tls.crt: |
  #   -----BEGIN CERTIFICATE-----
  #   Your server certificate content here
  #   -----END CERTIFICATE-----
  # tls.key: |
  #   -----BEGIN PRIVATE KEY-----
  #   Your server private key content here
  #   -----END PRIVATE KEY-----
  # ca.crt: |
  #   -----BEGIN CERTIFICATE-----
  #   Your CA certificate content here
  #   -----END CERTIFICATE-----
